services:
  db:
    image: postgres:17.0
    hostname: localhost
    ports:
      - "5432:5432" # map port 5432 on the container to port 5432 on the host
    environment:
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: